version: '3.1'

services:
  db:
    image: postgres:10.9
    container_name: postgresql
    env_file: .env
    ports:
      - "5432:5432"

  web:
    container_name: project
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    depends_on:
      - db
    links:
      - db:db