version: '3.1'

services:
  db:
    image: postgres:10.9
    container_name: postgresql
    env_file: .env
    ports:
      - "5432:5432"

  web:
    container_name: project
    restart: always
    build: .
    command: bash -c "cd src/ && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    depends_on:
      - db
    links:
      - db:db